<?php include('inc/header.php') ?>

<body class="d-flex flex-column "><main class="flex-shrink-0">

  <?php include('inc/menu.php') ?>
  <section class="page-header"><div class="container"><h1><?php echo policy;?></h1></div></section><div class="neos-contentcollection"><div class="section "><div class="container"><div class="row"><div class="col"><div class="neos-contentcollection"><div>

<p>A partir du 8 juillet 2020</p><p>Lors de la livraison de produits et en contact avec les clients, <?php echo websitename;?> traite des données personnelles. Votre vie privée est importante pour <?php echo websitename;?>. <?php echo websitename;?> respecte la loi sur la protection des données. Cela signifie que vos données personnelles sont en sécurité avec nous et que nous les utilisons toujours correctement. Dans cette politique de confidentialité, nous expliquons ce que nous faisons avec les données personnelles que nous recevons de vous. Si vous avez des questions ou souhaitez savoir exactement ce que nous conservons pour vous, veuillez contacter <?php echo websitename;?>.</p><p>&nbsp;</p><p>Finalités du traitement</p><p><?php echo websitename;?> traite vos données personnelles aux fins suivantes :</p><p>création de votre compte sur le site ;</p><p>souscription à un abonnement ;</p><p>traitement d'une commande ;</p><p>livraison de votre commande ;</p><p>envoi d'e-mails avec des offres ;</p><p>traitement des questions via le formulaire de contact ;</p><p>traitement des questions auprès du service client.</p><p>&nbsp;</p><p>1. Votre compte</p><p>Lors du processus de commande, vous devez d'abord vous inscrire. Vous devrez alors fournir des informations personnelles. Vous recevrez un compte utilisateur où vous pourrez vous connecter pour afficher, modifier et/ou supprimer des données. Nous utilisons votre nom, votre adresse, votre numéro de téléphone, votre adresse e-mail, votre adresse IP, votre adresse de facturation et vos informations de paiement. Nous avons besoin de ces informations dans le cadre du contrat que nous concluons avec vous. Nous conservons ces informations jusqu'à ce que vous supprimiez votre compte utilisateur, nous conservons également ces informations pour que vous n'ayez pas à tout remplir à chaque fois et pour pouvoir vous contacter plus facilement si nécessaire. Vous pouvez modifier les informations de votre compte à tout moment ou vous pouvez vous désabonner de votre compte.</p><p>&nbsp;</p><p>2. Souscription à un abonnement</p><p>Vous pouvez vous abonner chez nous, où nous utilisons vos données personnelles pour traiter le paiement. A cette fin, nous utilisons votre adresse de facturation, votre numéro de téléphone, vos coordonnées de paiement, votre adresse e-mail, votre nom et votre adresse et votre adresse IP.</p><p>Nous avons besoin de ces informations dans le cadre du contrat que nous concluons avec vous. Nous conservons ces informations pendant deux ans après la résiliation et sept ans après (obligation légale de conservation).</p><p>&nbsp;</p>

<p>3. Traitement des commandes</p><p>Lorsque vous passez une commande chez nous, nous utilisons vos données personnelles pour assurer le traitement correct de la commande. Nous pouvons ensuite transmettre vos données personnelles à notre service de livraison pour vous livrer la commande. Nous recevons également des informations sur votre paiement de votre banque ou de votre société de carte de crédit. À cette fin, nous utilisons vos coordonnées de paiement, votre nom et votre adresse, votre adresse IP, votre adresse e-mail, votre numéro de téléphone et votre adresse de facturation. Nous sommes légalement obligés de le faire. Nous conservons ces informations jusqu'à ce que votre commande soit terminée et sept ans après (conservation légale).</p><p> </p><p>6. Formulaire de contact</p><p>Vous pouvez nous poser des questions via le formulaire de contact. Lorsque vous utilisez le formulaire de contact, nous vous demandons vos coordonnées de client (adresse e-mail, numéro de téléphone, nom, adresse et numéro de client). Nous conservons ces informations jusqu'à ce que nous soyons sûrs que vous êtes satisfait de notre réponse, et jusqu'à six mois après. De cette façon, nous avons les informations à portée de main pour des questions de suivi. Cela nous permet également de former notre service client pour devenir encore meilleur.</p><p> </p><p>7. Service client</p><p>Notre service client est disponible par téléphone et par e-mail. Pour vous aider rapidement avec des questions, nous utilisons vos données et prenons des notes que nous conservons. Pratique si vous nous contactez à nouveau. Les détails de la conversation et/ou de l'échange de courriers électroniques avec vous seront enregistrés. De cette manière, vous nous aidez à analyser et à améliorer nos services. </p>

    <p>&nbsp;</p><p>Nos prestataires de services</p><p>Nous travaillons avec certaines entreprises qui peuvent recevoir vos données personnelles de notre part. À l'exception des partenaires décrits ci-dessus, nous ne transmettrons en aucun cas vos données personnelles à d'autres entreprises ou institutions, sauf si nous y sommes légalement obligés (par exemple, sur ordre de la police en cas de suspicion de crime).</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p><p>Cookies</p><p>Les sites web utilisent des cookies. Nous utilisons des cookies fonctionnels. Les cookies fonctionnels sont de petits fichiers que nous utilisons pour rendre le site web plus sûr et plus accessible. Lors de votre première visite sur le site web, nous affichons un message expliquant les cookies. Nous vous demandons votre autorisation pour utiliser ces cookies.</p><p>&nbsp;</p><p>La sécurité des données personnelles</p><p>La sécurité des données personnelles est très importante pour nous.</p><p>Pour protéger votre vie privée, nous prenons les mesures suivantes :</p><p>Dès réception, les données sont stockées dans un système séparé et protégé - nous prenons des mesures physiques telles que des serrures et des coffres-forts pour protéger l'accès aux systèmes dans lesquels les données personnelles sont stockées - nous utilisons des connexions sécurisées (Secure Sockets Layer ou SSL), qui stockent toutes les informations entre vous et notre site web lorsque vos informations personnelles sont saisies.</p><p>&nbsp;</p><p>Modifications de cette politique de confidentialité</p><p>Nous mettrons à jour cette déclaration de protection des données si nécessaire. Par conséquent, faites toujours attention à la date ci-dessus et vérifiez régulièrement les nouvelles versions. Nous ferons de notre mieux pour publier les modifications séparément.</p><p>&nbsp;</p><p>Inspection, modification et suppression de vos données</p><p>Si vous avez des questions ou si vous voulez savoir quelles données personnelles nous avons stockées à votre sujet, n'hésitez pas à nous contacter. Vous pouvez également nous demander de modifier ou de supprimer vos données. Si nous traitons vos données personnelles sur la base de votre consentement, vous pouvez toujours retirer votre consentement, après quoi nous cesserons le traitement.</p><p>Soyez toujours clair sur qui vous êtes pour que nous puissions être sûrs de corriger ou de supprimer les informations de la bonne personne.</p><p>&nbsp;</p>

<p>Déposer une plainte</p><p>Si vous pensez que nous ne vous aidons pas de la bonne manière, vous avez le droit de déposer une plainte auprès de l'autorité de contrôle, l'Autorité de protection des données des <?php echo payscompagnie;?>.</p><p>&nbsp;</p><p>Si vous avez des questions après avoir lu cette politique de confidentialité, vous pouvez nous contacter en utilisant les coordonnées ci-dessus.</p><h2><strong>Cookies</strong></h2><p>Les sites web utilisent des cookies. Nous utilisons des cookies fonctionnels. Les cookies fonctionnels sont de petits fichiers que nous utilisons pour rendre le site web plus sûr et plus accessible. Lors de votre première visite sur le site web, nous affichons un message expliquant les cookies. Nous demandons votre autorisation pour utiliser ces cookies.</p><p>Sécurité des données personnelles<br>La sécurité des données personnelles est très importante pour nous.<br>Pour protéger votre vie privée, nous prenons les mesures suivantes :<br>À réception, les données sont stockées dans un système séparé et protégé - nous prenons des mesures physiques telles que des verrous et des coffres-forts pour protéger l'accès aux systèmes dans lesquels les données personnelles sont stockées - nous utilisons des connexions sécurisées (Secure Sockets Layer ou SSL), qui stockent toutes les informations entre vous et notre site web lorsque vos informations personnelles sont saisies.</p><p>Changements apportés à cette politique de confidentialité<br>Nous mettrons à jour cette déclaration de protection des données si nécessaire. Par conséquent, soyez toujours attentif à la date ci-dessus et vérifiez régulièrement les nouvelles versions. Nous ferons de notre mieux pour publier les changements séparément.</p><p>Inspection, modification et suppression de vos données<br>Si vous avez des questions ou si vous souhaitez savoir quelles données personnelles nous avons stockées à votre sujet, n'hésitez pas à nous contacter. Vous pouvez également nous demander de modifier ou de supprimer vos données. Si nous traitons vos données personnelles sur la base de votre consentement, vous pouvez toujours retirer votre consentement, après quoi nous cesserons le traitement.<br>Soyez toujours clair sur votre identité afin que nous puissions être sûrs que nous corrigeons ou supprimons des informations de la bonne personne.</p><p>Déposer une plainte<br>Si vous pensez que nous ne vous aidons pas de la bonne manière, vous avez le droit de déposer une plainte auprès de l'autorité de contrôle, l'Autorité de protection des données des <?php echo payscompagnie;?>.</p><p>Si vous avez des questions après avoir lu cette politique de confidentialité, vous pouvez nous contacter en utilisant les coordonnées ci-dessus.</p><h2><strong>Klarna</strong></h2>


<p>Afin de vous proposer les modes de paiement de Klarna, nous pourrions, lors du processus de paiement, transmettre vos données personnelles sous forme de coordonnées et de détails de commande à Klarna, afin que Klarna puisse évaluer si vous êtes admissible à leurs modes de paiement et les personnaliser pour vous. Les données personnelles transmises sont traitées conformément à la politique de confidentialité de Klarna.<a rel="noopener external" href="https://www.klarna.com/international/privacy-policy/" target="_blank">Klarna’s own privacy notice</a>.</p>

  </div></div></div></div></div></div></div></main>


  <?php include('inc/footer.php') ?>

  <script async src="https://eu-library.klarnaservices.com/lib.js" data-client-id="282ae5c3-7477-59d3-ab49-3463fab8460c"></script>
  <script src="js/Main.js?bust=407c4aed"></script>
  <script src="js/main.min.js?bust=ef22ff16"></script>

  </body>

  </html>
